build-clang: Remove localinit sanitizer support for master branch
https://github.com/llvm-mirror/clang/commit/3eb970db6b61d0c310dd50cf4380f4045060b3ee

Signed-off-by: khusika <khusikadhamar@gmail.com>

diff --git a/build-clang b/build-clang
--- a/build-clang
+++ b/build-clang
@@ -237,9 +237,8 @@ function rollback() {
                 git cherry-pick 69ad28caf8 || die "There was an error rolling back ${FOLDER}!"
             else
                 git cherry-pick 24c9731717 || die "There was an error rolling back ${FOLDER}!"
-                git cherry-pick 176213e989 || die "There was an error rolling back ${FOLDER}!"
-                git cherry-pick 382ac69d5e || die "There was an error rolling back ${FOLDER}!"
-                git cherry-pick f50a8a1cf3 || die "There was an error rolling back ${FOLDER}!"
+                git cherry-pick 0ba332f771 || die "There was an error rolling back ${FOLDER}!"
+                git cherry-pick 9bb2dfc11c || die "There was an error rolling back ${FOLDER}!"
             fi
         fi
     fi
