build-clang: Add ability to rollback repos X amount of days
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: khusika <khusikadhamar@gmail.com>

diff --git a/build-clang b/build-clang
--- a/build-clang
+++ b/build-clang
@@ -143,6 +143,9 @@ function parse_parameters() {
             # OPTIONAL FLAGS
             "-b"|"--build-only")
                 BUILD_ONLY=true ;;
+            "-d"|"--date")
+                shift && enforce_value "${@}"
+                DATE_OFFSET=${1} ;;
             "-T"|"--test")
                 TEST=true ;;
             "-v"|"--version")
@@ -217,10 +220,14 @@ function sync() {
                     svn update ;;
                 *)
                     git clean -fxdq
-                    git checkout ${BRANCH}
-                    git fetch origin
-                    if ! git rebase origin/${BRANCH}; then
-                        die "Error updating $(basename "${FOLDER}")!"
+                    if [[ -n ${DATE_OFFSET} ]]; then
+                        git checkout "$(git log -1 --format=%H --before="$(date --date="-${DATE_OFFSET} day")")"
+                    else
+                        git checkout ${BRANCH}
+                        git fetch origin
+                        if ! git rebase origin/${BRANCH}; then
+                            die "Error updating $(basename "${FOLDER}")!"
+                        fi
                     fi ;;
             esac
         )
